server:
  port: 6443
  servlet:
    context-path: /uc

spring:
  profiles:
    active: prod
  application:
    name: usercenter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8888/eureka
    heartbeat-executor-thread-pool-size: 2
#    heartbeat-executor-exponential-back-off-bound:
  instance:
#    default-address-resolution-order: http://127.0.0.1:8888
logging:
  config: ${user.dir}/config/logback.xml
