server:
  port: 6443
  servlet:
    context-path: /uc

spring:
  application:
    name: usercenter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
#    default-address-resolution-order: http://127.0.0.1:8888
