server:
  port: 5555
  servlet:
    context-path: /consul

spring:
  application:
    name: consul-a
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
#      discovery:
#        enabled: false
#        register: true
#
#endpoints:
#  restart:
#    enabled: true
#
#management:
#  security:
#
#logging:
#  level:
#    org.springframework.cloud.consul: DEBUG

